create table if not exists public.works (
  id bigint generated by default as identity primary key,
  name text not null,
  material text not null default 'PLA',
  print_hours text not null default '—',
  color_method text not null default 'none'
    check (color_method in ('none', 'printed', 'painted')),
  description text not null default '',
  image_paths text[] not null default '{}',
  created_at timestamptz not null default now()
);

alter table public.works enable row level security;

drop policy if exists "Public can read works" on public.works;
create policy "Public can read works"
on public.works
for select
to anon
using (true);

insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public can read works images" on storage.objects;
create policy "Public can read works images"
on storage.objects
for select
to anon
using (bucket_id = 'images');
